trilobit:
    calculator:
        vars:
            trilobit: 123
            contao:
                partner:
                    - type: 'Webdesign'
                      test: 42
                      referenzen:
                          - 'du'
                          - 'ich'
                          - 'wir'
                    - type: 'Progammierung'
                      test: 2
                    - type: 'Schulung'
                      test: 3
            github: 'trilobit-gmbh'